In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [17]:
from sklearn.datasets import load_digits

In [18]:
df = load_digits()

In [19]:
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [64]:
X = df.data
Y  = df.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)

In [65]:
lr = LogisticRegression()
lr.fit(X_train,y_train)


c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [66]:
lr.score(X_test,y_test)

0.9861111111111112

In [67]:
svModel = SVC()
svModel.fit(X_train,y_train)

SVC()

In [68]:
svModel.score(X_test,y_test)

0.9888888888888889

In [69]:
RF  = RandomForestClassifier()
RF.fit(X_train,y_train)

RandomForestClassifier()

In [70]:
RF.score(X_test,y_test)

0.9888888888888889

## K Fold

In [71]:
from sklearn.model_selection import KFold
kf  =  KFold()

In [73]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [74]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [75]:
from sklearn.model_selection import StratifiedKFold
skfold  =  StratifiedKFold()

In [77]:
sc_L = []
sc_svc = []
sc_RF = []

for train_index, test_index in skfold.split(df.data,df.target):
    X_train, X_test, y_train, y_test = df.data[train_index],df.data[test_index],df.target[train_index],df.target[test_index]
    sc_L.append(get_score(lr,X_train, X_test, y_train, y_test))
    sc_svc.append(get_score(svModel,X_train, X_test, y_train, y_test))    
    sc_RF.append(get_score(RF,X_train, X_test, y_train, y_test))    

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

In [78]:
sc_L

[0.9222222222222223,
 0.8694444444444445,
 0.9415041782729805,
 0.9387186629526463,
 0.8969359331476323]

In [79]:

sc_svc

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [80]:
sc_RF

[0.9333333333333333,
 0.9083333333333333,
 0.958217270194986,
 0.9498607242339833,
 0.9192200557103064]

In [104]:
from sklearn.model_selection import cross_val_score

In [105]:
lrScore = []
svmScore = []
rfScore = []

lrScore.append(cross_val_score(lr,df.data,df.target))
svmScore.append(cross_val_score(svModel,df.data,df.target))
rfScore.append(cross_val_score(RF,df.data,df.target))

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

In [107]:
print("Scrore of LR =", lrScore)
print("Scrore of SVC =", svmScore) 
print("Scrore of RF =", rfScore)

Scrore of LR = [array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])]
Scrore of SVC = [array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])]
Scrore of RF = [array([0.92777778, 0.92222222, 0.95264624, 0.96657382, 0.92479109])]


In [108]:
from sklearn.datasets import load_iris
data =  load_iris()

In [109]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [110]:
lrIrisScore = []
svmIrisScore = []
rfIrisScore = []

lrIrisScore.append(cross_val_score(lr,data.data,data.target))
svmIrisScore.append(cross_val_score(svModel,data.data,data.target))
rfIrisScore.append(cross_val_score(RF,data.data,data.target))

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [111]:
print("Scrore of LR =", lrIrisScore)
print("Scrore of SVC =", svmIrisScore) 
print("Scrore of RF =", rfIrisScore)

Scrore of LR = [array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])]
Scrore of SVC = [array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])]
Scrore of RF = [array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])]
